\c lagger_dev;
ALTER TABLE IF EXISTS orders
ADD COLUMN IF NOT EXISTS CASES INT;

ALTER TABLE IF EXISTS notes
ADD COLUMN IF NOT EXISTS time_info varchar(12);

ALTER TABLE IF EXISTS notes
ALTER COLUMN date_info TYPE  varchar(14);
